#!/bin/bash

bold="%B"
reset="%f%b%k"

blue_fg="%F{blue}"
bold_blue_fg="%F{blue}%B"
green_fg="%F{green}"
bold_green_fg="%F{green}%B"
red_fg="%F{red}"
bold_red_fg="%F{red}%B"
yellow_fg="%F{yellow}"
bold_yellow_fg="%F{yellow}%B"
gray_fg="%F{black}"
bold_gray_fg="%F{black}%B"


blue_bg="%K{blue}"
green_bg="%K{greeb}"
red_bg="%K{red}"
yellow_bg="%K{yellow}"
gray_bg="%K{black}"

PROMPT_USER=%n
PROMPT_HOST=%m
PROMPT_DIR=%~
PROMPT_IND=%#
PROMPT_AT=@
PROMPT_OPEN=\[
PROMPT_CLOSE=\]


