#!/bin/sh

[[ $IS_BASH == true  ]]    &&  source ~/.rc/etc/prompt_definitions.d/bash_prompt_definitions
[[ $IS_ZSH == true  ]] &&  source ~/.rc/etc/prompt_definitions.d/zsh_prompt_definitions

BASIC="$bold$PROMPT_OPEN$PROMPT_USER$PROMPT_AT$PROMPT_HOST $PROMPT_DIR$PROMPT_CLOSE
>$reset "

MEDIUM="$bold$PROMPT_USER $reset$PROMPT_DIR
$bold>$reset "

MEDIUM_HOST_COLOR="$bold$PROMPT_USER $reset$bold_gray_fg$PROMPT_HOST $reset$bold_blue_fg$PROMPT_DIR$reset
$bold_fg>$reset "

MEDIUM_COLOR="$bold$PROMPT_USER $reset$bold_blue_fg$PROMPT_DIR$reset
$bold_fg>$reset "

POWERLINE="$bold_blue_bg $PROMPT_USER $reset $gray_fg$PROMPT_HOST $bold$PROMPT_DIR
$bold_blue_fg> $reset"

POWERLINE_LITE="$bold_blue_bg $PROMPT_USER $reset $gray_fg$PROMPT_DIR
$bold_blue_fg> $reset"

REDHAT_COLORED="$reset$PROMPT_OPEN$bold_green_fg$PROMPT_USER$reset$PROMPT_AT$green_fg$PROMPT_HOST $gray_fg$PROMPT_DIR$reset$PROMPT_CLOSE$PROMPT_IND "

MINI_GRAY="$reset$PROMPT_OPEN$gray_fg$PROMPT_USER$reset $bold_gray_fg$PROMPT_DIR$reset$PROMPT_CLOSE$PROMPT_IND "

MINI_COLOR="$bold_green_fg$PROMPT_OPEN$reset$bold$PROMPT_USER$reset $bold_gray_fg$PROMPT_DIR$bold_green_fg$PROMPT_CLOSE$reset$bold$PROMPT_IND$reset "


__dynamic_prompt() {
	rc=$?
	RCC=""
	if [[  $rc != 0 ]]; then
		RCC="$reset$red_fg"
	else
		RCC="$reset$green_fg"
	fi

	PS1="$bold$PROMPT_OPEN$bold_green_fg$PROMPT_USER$reset$PROMPT_AT$bold_yellow_fg$PROMPT_HOST$reset:$bold_blue_fg$PROMPT_DIR$reset$bold$PROMPT_CLOSE$RCC$PROMPT_IND$reset "
}
