#!/bin/bash

bold="\[\033[1;1m\]"
reset="\[\033[0;0m\]"

blue_fg="\[\033[0;34m\]"
bold_blue_fg="\[\033[1;34m\]"
green_fg="\[\033[0;32m\]"
bold_green_fg="\[\033[1;32m\]"
red_fg="\[\033[0;31m\]"
bold_red_fg="\[\033[1;31m\]"
yellow_fg="\[\033[0;33m\]"
bold_yellow_fg="\[\033[1;33m\]"
gray_fg="\[\033[0;37m\]"
bold_gray_fg="\[\033[1;30m\]"


blue_bg="\[\033[0;44m\]"
bold_blue_bg="\[\033[1;44m\]"
green_bg="\[\033[0;42m\]"
red_bg="\[\033[0;41m\]"
yellow_bg="\[\033[0;43m\]"
gray_bg="\[\033[0;47m\]"

PROMPT_USER=\\u
PROMPT_HOST=\\h
PROMPT_DIR=\\w
PROMPT_IND=\\$
PROMPT_AT=@
PROMPT_OPEN=[
PROMPT_CLOSE=]




